# Generated by Django 4.2.6 on 2023-11-21 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(default='CqujGsrGLWAH6A0gt9KnvquHY1DwlCp8', max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 21, 6, 15, 933818, tzinfo=datetime.timezone.utc)),
        ),
    ]
