# Generated by Django 4.2.6 on 2023-11-21 20:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(editable=False, max_length=10, null=True, unique=True)),
                ('pack_name', models.CharField(max_length=255)),
                ('pack_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pack_image', models.URLField(max_length=500)),
                ('pack_type', models.CharField(max_length=255)),
                ('pack_product_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(editable=False, max_length=10, null=True, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('product_variants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('product_image', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_products', to='products_api_v1.pack')),
            ],
        ),
    ]
